spring:
  application:
    name: nativeredispruebaconcepto
  profiles:
    active: dev

---
spring:
  cloud:
    gcp:
      project-id: gcp-mutualser-rdfs-dev
      credentials:
        encoded-key: ew0KICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAicHJvamVjdF9pZCI6ICJnY3AtbXV0dWFsc2VyLXJkZnMtZGV2IiwNCiAgInByaXZhdGVfa2V5X2lkIjogIjA1YTBlYTg5ZDhjZGI4YzA0OTBiYzcxNTYxNDFjOTg2ODRjYzBkOGMiLA0KICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM1Ylh0aEZMbGxaaHBZXG5vMkRKZU55UDd0TWthUUVqb244RDNKanZiZFBYanU0aThaQjRCSUFLdEtwdHBHYk1PYndCdGVYeENZOUZyeVh6XG53TlRHV3NpM2ZFZEJyVDNZTjJGMDF4YUxPakwrbDVPeFg0Yk5ZMEI0NGVZQ29XMmdSZnBLbDROMjJMYTQrazMrXG5NRG9iS0piWjRRN3VWTW1zL1ZWbmVOY040V0lHRlVYa2ExeGlhRnZrY3IxZjZRTkg3RXRrb0xGRGo5YUlSaUUzXG5BanRsSHVoUDZOa2dKc3RHQnZnWlZ2VCtKclhGMVJtdkw5QmhvQWgvWkJ3NG9MRzJ4dURJWkkvZVdPMG1oV25yXG5SWTRObjV6OG9nTHFTRUp5d1NYR0g2ZTR5RzZsaU9Ga3hxM0lENnFuenNRdWJ5dmVVTEVxQTRRSzJuQU1rQm5OXG5mRy9YYlR6MUFnTUJBQUVDZ2dFQUhhVFdXT3ljZ0F5czhSYzdjYklvQnIydVZTK1JUazViNG5UcG9UdHNadFZ6XG5salFLdmRrd1ZDWFNha0ZpYXN0ZkZtSHJYeGZCWnlsTFZyYncvVDRGd1NtMTVaYko0STluL2VzbDhEK3ZaOXE1XG5NcDNjT2VrZ1pVTHVCK1VoVnNKaE0zd1orUTNIMW5ZenNrdW8rbThJZ05BVldENUhXS2ZPZDhLT2xPby9oc3VwXG5yQmFsdEI1NlYvb1dBRXlLU2YxRXNXKy9XQ3p3bS9oZjBrcU9DZjlDQktod1hDMWxQNEFhTW5FL09iK2hWNElBXG5rbjVUVHUyLzg1Y2NNT1czVm5wM2tUSWVEV2dPZGp0NnhNWmFsS0xlTmIvL0RXNFdjNWlkdHNqclZYb0NWYkUrXG5tMGVjNTkrUTM0UjkrSjdlNEdTWEVmU3FVcGZyZGNPdHdKMkt1Wi9EV1FLQmdRRGNXSTVQeThQa3pxb0lkYXNwXG5RZ3I3UGE4K3ZRZ0RLRng3enB5b0syL2RvT1BOcWFNTnpicGlVWXBKcW52VlZaakdjMnE5STFPNFQ1R3lZM3hkXG44RWd5YmdrRGMvTUNzZ2dHbGwxdWhtQjY1TmUyY3dJbFY3MG80ZlQzYWRSakhUR0lUcnpVQjF4RUhIV21ITzAyXG5HV210bm81QklZai94cndDbVE3OUw1Uno2UUtCZ1FEWGJuK1RoOE9OVnVDcnQrelRvNDZHejlUb1p4Q2k1TmJ0XG53alRoNjJWN3JpV3hzak5MR08vMUhVTzJrcGdxREZxTVF5VXZRMGY4T1VCOHdhYnJzRGRGbTJQWUJwVS9YS004XG5jRngvekU5dG9KOEFKSENIR0dNazZRbStLS3RTZWtKZE82K005UlRsNHJpTTUyVEMrSU9CK2hDRkRjRmVjWmt4XG5QTytBVEVUVkxRS0JnUURiMXBhVjBteXRtZXRXNlY5Tm1KQ3dQY2pjUldqN0RZZklGa21DRjJSU3NMVFhla290XG4rWFhkcGhEY2tuVmVVVHBOdE5Wbnd4bENLRkRxdEF0ZkJkNWlRaHBJRWFVQXFYTU1iM1RrVXJscm8ybjhwQjRkXG45NzNJVGpoRHFKaTRFbVphNG9QTzMxRVV1M2c5dFZxTndTa0lpY3JQL0k5YzhZQ2U3dXBmZk5zV0VRS0JnQWh1XG5mYlhEZVliZG9KdDM3bC8ySmN6bTgzbEpGMkNZdmtTOTloM2xmYXBTalkwZjRWd09GTTR1SUFsVVFYcGIwMnRyXG44VmVoTlg4TXFwWjNhZFlOcG93bDRjbUJzSE96WjN3bEZhbTIwR0VGQ1ZRVEdRaGdqdmpSMmh6RU1MaGdxcHBGXG5qTUJpa3pmUUlOTDY5M21lQ2wrYTd1eVdOanhCQy9MZVpLMUx6dUhkQW9HQkFOZ0RBZVN3S3dYMlB3REM1cnpXXG55ZHBtc2d6UnNmeXpYYnZyZzhaSU96ZWQ0blB0VWtOWFlrYVNuUzFKRmszcHFsMEVPSDlwd3YwS2tVTWE0N1g2XG5mbUwwUFlYSzYxVWFRSUJJd2tpeEY3bGtQck56dm1TZGg5VnZ2ZHVMR1g3SEJmTE0wZnVGdkhQaUNXVWxXYVlPXG5RMmp4Q3lneHhkYW9BeHZkcEVObTB6eFhcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsDQogICJjbGllbnRfZW1haWwiOiAiZ2NwLW11dHVhbHNlci1yZGZzLWRldkBhcHBzcG90LmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAiY2xpZW50X2lkIjogIjEwMTMwNzY2MDgzNzM1NTAyNDAxOSIsDQogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsDQogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLA0KICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsDQogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2djcC1tdXR1YWxzZXItcmRmcy1kZXYlNDBhcHBzcG90LmdzZXJ2aWNlYWNjb3VudC5jb20iDQp9DQo=
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.212.25:3306/lacerta?useSSL=false&&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: userrips
    password: DzG1qwnNF4odxDEV
    hikari:
      maximumPoolSize: 100
      minimumIdle: 50
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 600000
      connection-timeout: 6000
      max-lifetime: 0
      idle-timeout: 10000
      keepalive-time: 30000
      connection-init-sql: SELECT 1 FROM dual
      connection-test-query: SELECT 1 FROM dual
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update